# Generated by Django 5.2.4 on 2025-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
